name: Nightly

on:
  push:
    branches: [ master ]

jobs:
  nightly:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, bin: target/release/cpkg, name: cpkg (linux x64) }
          - { os: windows-latest, bin: target/release/cpkg.exe, name: cpkg (windows x64) }

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}
          path: ${{ matrix.config.bin }}