name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, bin: target/release/cpkg }
          - { os: windows-latest, bin: target/release/cpkg.exe }

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.config.bin }}